Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -26,9 +26,18 @@ jobs:
       run: ./gradlew build
       
     - name: Build and Test
+      run: ./gradlew --info test
 #      with:
 #         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
 #         aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
 #         aws-region: ap-northeast-2
-      run: |
-         mvn clean test -Ptest -DSpring.profiles.active=test
+
+     # Test Result
+    - name: Report Unit Test Result
+      uses: dorny/test-reporter@v1
+      if: always()  # success() || failure()
+      with:
+       name: Test Result
+       path: target/reports/*.xml
+       reporter: java-junit
+       fail-on-error: true
